/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComunidadesRouteImport } from './routes/comunidades'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedConsultasRouteImport } from './routes/_authenticated/consultas'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedExperienciaProtegidaRouteImport } from './routes/_authenticated/experiencia-protegida'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedMeuEspacoRouteImport } from './routes/_authenticated/meu-espaco'
import { Route as AuthenticatedModeracaoRouteImport } from './routes/_authenticated/moderacao'
import { Route as AuthenticatedPainelProfissionalRouteImport } from './routes/_authenticated/painel-profissional'
import { Route as AprenderSlugRouteImport } from './routes/aprender.$slug'
import { Route as ComunidadesSlugRouteImport } from './routes/comunidades.$slug'
import { Route as ProfissionaisIdRouteImport } from './routes/profissionais.$id'
import { Route as PublicacoesIdRouteImport } from './routes/publicacoes.$id'
import { Route as AuthenticatedPerfilIdRouteImport } from './routes/_authenticated/perfil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadesRoute = ComunidadesRouteImport.update({
  id: '/comunidades',
  path: '/comunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultasRoute = AuthenticatedConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperienciaProtegidaRoute =
  AuthenticatedExperienciaProtegidaRouteImport.update({
    id: '/experiencia-protegida',
    path: '/experiencia-protegida',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuEspacoRoute = AuthenticatedMeuEspacoRouteImport.update({
  id: '/meu-espaco',
  path: '/meu-espaco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModeracaoRoute = AuthenticatedModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelProfissionalRoute =
  AuthenticatedPainelProfissionalRouteImport.update({
    id: '/painel-profissional',
    path: '/painel-profissional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AprenderSlugRoute = AprenderSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AprenderRoute,
} as any)
const ComunidadesSlugRoute = ComunidadesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComunidadesRoute,
} as any)
const ProfissionaisIdRoute = ProfissionaisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfissionaisRoute,
} as any)
const PublicacoesIdRoute = PublicacoesIdRouteImport.update({
  id: '/publicacoes/$id',
  path: '/publicacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilIdRoute = AuthenticatedPerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/aprender': typeof AprenderRouteWithChildren
  '/auth': typeof AuthRoute
  '/comunidades': typeof ComunidadesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/consultas': typeof AuthenticatedConsultasRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/experiencia-protegida': typeof AuthenticatedExperienciaProtegidaRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/meu-espaco': typeof AuthenticatedMeuEspacoRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/painel-profissional': typeof AuthenticatedPainelProfissionalRoute
  '/aprender/$slug': typeof AprenderSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/publicacoes/$id': typeof PublicacoesIdRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/aprender': typeof AprenderRouteWithChildren
  '/auth': typeof AuthRoute
  '/comunidades': typeof ComunidadesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/consultas': typeof AuthenticatedConsultasRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/experiencia-protegida': typeof AuthenticatedExperienciaProtegidaRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/meu-espaco': typeof AuthenticatedMeuEspacoRoute
  '/moderacao': typeof AuthenticatedModeracaoRoute
  '/painel-profissional': typeof AuthenticatedPainelProfissionalRoute
  '/aprender/$slug': typeof AprenderSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/publicacoes/$id': typeof PublicacoesIdRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/aprender': typeof AprenderRouteWithChildren
  '/auth': typeof AuthRoute
  '/comunidades': typeof ComunidadesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/profissionais': typeof ProfissionaisRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/consultas': typeof AuthenticatedConsultasRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/experiencia-protegida': typeof AuthenticatedExperienciaProtegidaRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/meu-espaco': typeof AuthenticatedMeuEspacoRoute
  '/_authenticated/moderacao': typeof AuthenticatedModeracaoRoute
  '/_authenticated/painel-profissional': typeof AuthenticatedPainelProfissionalRoute
  '/aprender/$slug': typeof AprenderSlugRoute
  '/comunidades/$slug': typeof ComunidadesSlugRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/publicacoes/$id': typeof PublicacoesIdRoute
  '/_authenticated/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/aprender'
    | '/auth'
    | '/comunidades'
    | '/privacidade'
    | '/profissionais'
    | '/admin'
    | '/consultas'
    | '/criar'
    | '/diario'
    | '/experiencia-protegida'
    | '/feed'
    | '/mensagens'
    | '/meu-espaco'
    | '/moderacao'
    | '/painel-profissional'
    | '/aprender/$slug'
    | '/comunidades/$slug'
    | '/profissionais/$id'
    | '/publicacoes/$id'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/aprender'
    | '/auth'
    | '/comunidades'
    | '/privacidade'
    | '/profissionais'
    | '/admin'
    | '/consultas'
    | '/criar'
    | '/diario'
    | '/experiencia-protegida'
    | '/feed'
    | '/mensagens'
    | '/meu-espaco'
    | '/moderacao'
    | '/painel-profissional'
    | '/aprender/$slug'
    | '/comunidades/$slug'
    | '/profissionais/$id'
    | '/publicacoes/$id'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/aprender'
    | '/auth'
    | '/comunidades'
    | '/privacidade'
    | '/profissionais'
    | '/_authenticated/admin'
    | '/_authenticated/consultas'
    | '/_authenticated/criar'
    | '/_authenticated/diario'
    | '/_authenticated/experiencia-protegida'
    | '/_authenticated/feed'
    | '/_authenticated/mensagens'
    | '/_authenticated/meu-espaco'
    | '/_authenticated/moderacao'
    | '/_authenticated/painel-profissional'
    | '/aprender/$slug'
    | '/comunidades/$slug'
    | '/profissionais/$id'
    | '/publicacoes/$id'
    | '/_authenticated/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  AprenderRoute: typeof AprenderRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComunidadesRoute: typeof ComunidadesRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfissionaisRoute: typeof ProfissionaisRouteWithChildren
  PublicacoesIdRoute: typeof PublicacoesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidades': {
      id: '/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof ComunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultas': {
      id: '/_authenticated/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof AuthenticatedConsultasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiencia-protegida': {
      id: '/_authenticated/experiencia-protegida'
      path: '/experiencia-protegida'
      fullPath: '/experiencia-protegida'
      preLoaderRoute: typeof AuthenticatedExperienciaProtegidaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-espaco': {
      id: '/_authenticated/meu-espaco'
      path: '/meu-espaco'
      fullPath: '/meu-espaco'
      preLoaderRoute: typeof AuthenticatedMeuEspacoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderacao': {
      id: '/_authenticated/moderacao'
      path: '/moderacao'
      fullPath: '/moderacao'
      preLoaderRoute: typeof AuthenticatedModeracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-profissional': {
      id: '/_authenticated/painel-profissional'
      path: '/painel-profissional'
      fullPath: '/painel-profissional'
      preLoaderRoute: typeof AuthenticatedPainelProfissionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/aprender/$slug': {
      id: '/aprender/$slug'
      path: '/$slug'
      fullPath: '/aprender/$slug'
      preLoaderRoute: typeof AprenderSlugRouteImport
      parentRoute: typeof AprenderRoute
    }
    '/comunidades/$slug': {
      id: '/comunidades/$slug'
      path: '/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof ComunidadesSlugRouteImport
      parentRoute: typeof ComunidadesRoute
    }
    '/profissionais/$id': {
      id: '/profissionais/$id'
      path: '/$id'
      fullPath: '/profissionais/$id'
      preLoaderRoute: typeof ProfissionaisIdRouteImport
      parentRoute: typeof ProfissionaisRoute
    }
    '/publicacoes/$id': {
      id: '/publicacoes/$id'
      path: '/publicacoes/$id'
      fullPath: '/publicacoes/$id'
      preLoaderRoute: typeof PublicacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil/$id': {
      id: '/_authenticated/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof AuthenticatedPerfilIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConsultasRoute: typeof AuthenticatedConsultasRoute
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedExperienciaProtegidaRoute: typeof AuthenticatedExperienciaProtegidaRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedMeuEspacoRoute: typeof AuthenticatedMeuEspacoRoute
  AuthenticatedModeracaoRoute: typeof AuthenticatedModeracaoRoute
  AuthenticatedPainelProfissionalRoute: typeof AuthenticatedPainelProfissionalRoute
  AuthenticatedPerfilIdRoute: typeof AuthenticatedPerfilIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConsultasRoute: AuthenticatedConsultasRoute,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedExperienciaProtegidaRoute:
    AuthenticatedExperienciaProtegidaRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedMeuEspacoRoute: AuthenticatedMeuEspacoRoute,
  AuthenticatedModeracaoRoute: AuthenticatedModeracaoRoute,
  AuthenticatedPainelProfissionalRoute: AuthenticatedPainelProfissionalRoute,
  AuthenticatedPerfilIdRoute: AuthenticatedPerfilIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AprenderRouteChildren {
  AprenderSlugRoute: typeof AprenderSlugRoute
}

const AprenderRouteChildren: AprenderRouteChildren = {
  AprenderSlugRoute: AprenderSlugRoute,
}

const AprenderRouteWithChildren = AprenderRoute._addFileChildren(
  AprenderRouteChildren,
)

interface ComunidadesRouteChildren {
  ComunidadesSlugRoute: typeof ComunidadesSlugRoute
}

const ComunidadesRouteChildren: ComunidadesRouteChildren = {
  ComunidadesSlugRoute: ComunidadesSlugRoute,
}

const ComunidadesRouteWithChildren = ComunidadesRoute._addFileChildren(
  ComunidadesRouteChildren,
)

interface ProfissionaisRouteChildren {
  ProfissionaisIdRoute: typeof ProfissionaisIdRoute
}

const ProfissionaisRouteChildren: ProfissionaisRouteChildren = {
  ProfissionaisIdRoute: ProfissionaisIdRoute,
}

const ProfissionaisRouteWithChildren = ProfissionaisRoute._addFileChildren(
  ProfissionaisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AjudaRoute: AjudaRoute,
  AprenderRoute: AprenderRouteWithChildren,
  AuthRoute: AuthRoute,
  ComunidadesRoute: ComunidadesRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfissionaisRoute: ProfissionaisRouteWithChildren,
  PublicacoesIdRoute: PublicacoesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
